### ISSUE TITLE
Fix HHVM crashes

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/puppet#79]
Likely the cause: https://phabricator.wikimedia.org/T123536.

After the MediaWiki 1.26 upgrade, I cannot remember any millisecond HHVM *did* work.

@JohnFLewis please advise us in fixing this annoying bug.

**Comment by JohnFLewis** [comment]
It's likely how MW interacts with HHVM that causes the issue, not HHVM itself.

**Comment by JohnFLewis** [comment]
Resolved?

**Comment by Southparkfan** [comment]
Nope. HHVM 3.6 still crashes regularly.

3.6, 3.9, according to https://phabricator.wikimedia.org/T126871 3.12 too: it just doesn't work.

**Comment by JohnFLewis** [comment]
Regular crashes are due to OOM.

3.9 experienced no issues with MW1.26 on mw1, 3.12 threw out errors because of LiquidThreads but were non-fatal and it ran longer than HHVM 3.9 did. eventually it died because of a OOM. SO calling this issue technically solved.
